### ISSUE TITLE
Anki web may suspend account when using the chrome extention

### ISSUE THREAD

**Issue by Zkffkah** [ninja33/anki-dict-helper#10]
When trying to add a new word to ankiweb using this extention today, it shows an error that it can't connect to anki web.
It turn out that the account is temporary suspend by ankiweb. Following is the message.

> Account Suspended
> 
> Your account has been suspended for violating AnkiWeb's terms of service. As mentioned in the terms 
> that you agreed to when creating an account, automated access to AnkiWeb is currently not allowed, as > it uses a disproportionate amount of server resources, and creates headaches for us when invalid data is > posted.
> Your account will be reinstated in 24 hours. Please avoid accessing the site programmatically in the 
> future, as future violations may result in the removal of your account.

I was wondering what your thoughts about the cause of this problem?
Is it related that I'm using the anki-droid app in my Android phone too and editing the card there .
Did you face this problem before and how can I avoid this in the future?

Thanks in advance!

**Comment by ninja33** [comment]
Yes, You are right. I got the same problem as you yesterday.

I quoted part of  FAQ from [Yomichan Chrome](https://github.com/FooSoft/yomichan-chrome) project here as reference.
> #### What happened to AnkiWeb integration? Why was it removed?
> 
> The author of Anki wants to maintain tight control of AnkiWeb by restricting automated web requests, while at the same time not providing an API for adding or removing flash cards. As circumventing these restrictions led to account restrictions placed on users of this extension, I was forced to remove this feature. Note that it is still possible to automatically generate flashcards with the AnkiConnect plugin.

That's why I upgraded this extension to 0.99.6 last night which disabled ankiweb interface. 
Please use anki-connect interface instead.

**Comment by FooSoft** [comment]
Yup, definitely a setback but we'll manage. I've downloaded the beta of the new Anki, and while things are broken out of the box (the PyQt4 import), I think everything else should work fine. Hopefully get a cross-version compatible release done this weekend.

**Comment by Zkffkah** [comment]
Since I never use the anki desktop to review cards, it's really redundant to install an anki desktop and start a local ankiconnect service for adding cards. Could we add some workaround to pass the robot detection? Maybe a user agent in the header? Or micmic the user interaction by a request to the website edit page first and then the save request? I think it's ok to add this since this is just a automated process of the manual operation but not a malicious attack to the website. It has no difference with doing it by hand but we let the extention do it for us.

**Comment by ninja33** [comment]
It's been tried already. Each time we fixed it, Ankiweb then upgraded its interface to restrict this kind of behavior. That means he is serious. Even more seriously, extension users accounts are now at risk of being suspended. 

For more detail discussion about this topic, you may go Anki official supporting forum and find this thread: https://anki.tenderapp.com/discussions/ankiweb/1886-issue-with-saving-cards-via-rest-api

Sorry for the inconvenience.

**Comment by Zkffkah** [comment]
Understood. Sorry for their choice but thank you for your kind support anyway.
