### ISSUE TITLE
本地文件用浏览器打开时插件不能使用

### ISSUE THREAD

**Issue by Edenharder** [ninja33/anki-dict-helper#11]
把本地的文件如`txt, pdf, html`用浏览器打开后，尝试使用插件无效。希望能增加这一功能，这样也解决了本地文件划词添加到anki的问题。

**Comment by ninja33** [comment]
你可以在chrome插件管理页面，点击“访问本地文件”的权限

**Comment by Edenharder** [comment]
对txt可行，但对pdf不行。

**Comment by ninja33** [comment]
对PDF，请先使用[PDF.js](https://github.com/mozilla/pdf.js) 打开文章后，再使用划词助手。
你可以在他那个[online demo](https://mozilla.github.io/pdf.js/web/viewer.html)上划词试试看。
另外，对于图片扫描版的PDF，其中的文字其实是图片，所以不可划词。
