### ISSUE TITLE
能否添加”划词“翻译的选项？

### ISSUE THREAD

**Issue by Edenharder** [ninja33/anki-dict-helper#12]
现在已有的功能是在光标处自动扫描判断单词，这对于文本被正确渲染时是没有问题的。但在pdf中有时渲染会莫名奇妙多出空格，当然这是pdf.js的问题，然而pdf.js那里一直没有解决这个问题。在这个插件里能否添加对划词部分(选定部分)翻译的选项呢？对划词部分复制并删除单词字母间的空格，然后查找翻译。

**Comment by ninja33** [comment]
有兴趣的话，可以去看看我的新插件。支持手动选中单词。

https://github.com/ninja33/anki-online-dict-helper
