### ISSUE TITLE
不能查片語，很可惜

### ISSUE THREAD

**Issue by i14d14** [ninja33/anki-dict-helper#15]
非常棒的軟體，可惜不能查片語

**Comment by ninja33** [comment]
I think it supports phrase,  but not always.
phrase is a bit complicate to "match", especially when it has pronoun(someone, something).

![capture](https://cloud.githubusercontent.com/assets/20181220/25321760/c339b170-28e3-11e7-9fe6-d3db9fd5be5a.png)

**Comment by ninja33** [comment]
因为是自动选择，所以只能自动判断是否是短语。

有兴趣的话可以看看我的新插件，原来的shift自动选择，也支持双击选择，和完全手动选择。
https://github.com/ninja33/anki-online-dict-helper
