### ISSUE TITLE
允许手工选择短语

### ISSUE THREAD

**Issue by flyisland** [ninja33/anki-dict-helper#19]
允许手工选择单词，现在这种方式一般只会选一个词，但很多时候是需要记忆短语（多个单词一起）

**Comment by luboq** [comment]
建议+1
相关issue： #12 #15 　
不过pr只有一个，全靠ninja33也确实挺过意不去的

![截图](http://onuia4d7l.bkt.clouddn.com/2017_07_23_222.gif)

**Comment by ninja33** [comment]
其实这版划词助手，主要都是从yomichan改的，有些代码已经难以维护。

全部从新制作的在线版增加了手工选择。
https://github.com/ninja33/anki-online-dict-helper
