### ISSUE TITLE
README 加上Firefox扩展的地址

### ISSUE THREAD

**Issue by luboq** [ninja33/anki-dict-helper#21]
知乎、项目主页等全部地方，都只说Chrome地址，没提Firefox，所以误以为没有Firefox扩展呢
看到Firefox分支，还以为暂停开发中
最后，从firefox分支源码编译出了扩展，安装后，firefox自己识别出了市场里的地址：
https://addons.mozilla.org/zh-CN/firefox/addon/anki-%E5%88%92%E8%AF%8D%E5%88%B6%E5%8D%A1%E5%8A%A9%E6%89%8B/
点进去才知道，原来有Firefox扩展。而且使用后，一切正常。

为什么主页不添加Firefox版本的地址呢？建议加上

**Comment by biluohc** [comment]
Fx用户支持一个,希望作者不要放弃Fx分支.

**Comment by ninja33** [comment]
主要是firefox在有些javascript的标准上没有支持到较新版本。另外ff的审核相当费时间。

目前还是主要在支持chrome版本。

有兴趣的话， 也可以看看最新的在线版划词助手。

https://github.com/ninja33/anki-online-dict-helper
