### ISSUE TITLE
希望适配简悦

### ISSUE THREAD

**Issue by Kenshin** [ninja33/anki-dict-helper#22]
你好，我是 [简悦](https://github.com/Kenshin/simpread) 的作者，简悦是一个 Chrome 下的阅读模式。
我很喜欢这个扩展，但与简悦在一起使用时会有个问题，希望能得到解决。

简悦的 `阅读模式` 为了避免 CSS污染，所以没有在 `<body>` 里面生成标签，所以当使用 `简悦的阅读模式` 后，无法弹出。

所以希望把 anki 的扩展放到 <html> 标签下，即应该可以解决问题。

**Comment by ninja33** [comment]
看了你的简悦项目，你是懂js的前端工程师把？
这个项目是我自己学习用的一个小工具，我不太懂js，也没时间维护。
你要不发个PR，我merge了。

**Comment by ninja33** [comment]
尝试放在simproot下面，大概是这个样子。

![simpread](https://user-images.githubusercontent.com/20181220/35482909-7aee3f7a-0476-11e8-9798-1c2f4b52d9ed.png)

我会更新在新版插件里。
https://github.com/ninja33/anki-online-dict-helper

**Comment by Kenshin** [comment]
Cool~ 感谢适配，我会帮忙宣传一下！
