### ISSUE TITLE
0.99.6版与AnkiConnect不兼容

### ISSUE THREAD

**Issue by mapx** [ninja33/anki-dict-helper#24]
浏览器：火狐 57
插件版本：0.99.6
Anki版本：2.0.47

使用 https://ninja33.github.io/20160817/anki-connect/ 及 https://ankiweb.net/shared/info/2055492159 的 AnkiConnect 均显示不兼容

谢谢！

**Comment by ninja33** [comment]
把ankiconnect.py文件里的版本号改成1就好了。

**Comment by paliukun** [comment]
遇到了同样的问题哎，改成1好像也没用。。

**Comment by ninja33** [comment]
可以看看这里。
http://www.laohuang.net/20160817/ankiconnect-py-file/

另外，可以看看新版的在线版本插件
https://github.com/ninja33/anki-online-dict-helper
