### ISSUE TITLE
划词助手间歇性失灵

### ISSUE THREAD

**Issue by thereisnowinter** [ninja33/anki-dict-helper#26]
不知道为什么,这个划词助手,偶尔有用,偶尔没有用.

这个能解决吗?

谢谢!

**Comment by ninja33** [comment]
划词助手需要页面完全加载完毕才可以取词。如果你需要的看的网页文字已经加载完毕，但是还有其他图片，广告等信息使得浏览器加载指示图标，还在转圈，你可以点X，使浏览器停止加载。
