### ISSUE TITLE
中文无法正常显示

### ISSUE THREAD

**Issue by AlviraC** [ninja33/anki-dict-helper#27]
在手机上捕获的卡片。
在电脑上学习时，英文和音标可以正常显示，但是中文无法正常显示（显示为一个个方框）
系统是win10

**Comment by AlviraC** [comment]
<style>
/*global card style*/
.card {
  font-family          : helvetica, arial, sans-serif;
  font-size              : 16px;
  text-align             : left;
  color                     : #1d2129; 
  background-color : #e9ebee;
}

把以上这段的helvetica删去后，win10上可以正常显示中文。

为何原来有helvetica的时候，anki安卓客户端上可以正常显示，win10上却不行？

**Comment by ninja33** [comment]
可能是内置字体的问题。因为有些字体在系统内并没有内置。但这不是插件的bug。
