### ISSUE TITLE
Chrome 0.99.7与Anki不兼容

### ISSUE THREAD

**Issue by lyylmm** [ninja33/anki-dict-helper#29]
Anki版本：2.0.48
Chrome显示:
不支持的版本: 当前Anki PC客户端所安装的 AnkiConnect 插件版本于制卡助手不兼容，请更新

**Comment by ninja33** [comment]
去下面这个地址下载一个2.0的ankiconnect就好了
http://www.laohuang.net/20160817/ankiconnect-py-file/
