### ISSUE TITLE
请问如何使用划词助手出英英释义

### ISSUE THREAD

**Issue by jiexishede** [ninja33/anki-dict-helper#31]
![image](https://user-images.githubusercontent.com/9484734/34932011-44d9edb8-fa0c-11e7-935d-4eb0739fd0f5.png)

看了　视频中是有　英英释义的　　
　
我个人做的　是　这个位置是　词典响应的　例句，　

我想改成英英　释义　怎么做？？　

![image](https://user-images.githubusercontent.com/9484734/34932058-6db4640c-fa0c-11e7-9777-930686165d24.png)

我打开　中国日报的这个　网址　是这样的。。。

![image](https://user-images.githubusercontent.com/9484734/34932715-fa59cb0c-fa0e-11e7-827e-161be8cf42d4.png)

**Comment by ninja33** [comment]
这是两本词典。一本是collins词典，一本是新牛津第二版。
因为chrome商店的插件不能随便更换词典，所以商店版本用了较小的collins词典。
