### ISSUE TITLE
支持Anki ConnectV5.0；能否像Pocket一样将内容直接保存到Anki

### ISSUE THREAD

**Issue by FreeSlaver** [ninja33/anki-dict-helper#32]
你好，看到了Chrome上的留言，只支持Anki ConnectV2.0，能否支持V5.0的了？
还有就是能够添加一个功能，将一段文本直接保存到Anki中阅读吗？

**Comment by ninja33** [comment]
添加文本并阅读不是划词助手的功能。划词助手只是将所划单词的句子加入anki。

ankiconnect的版本问题，主要是因为ankiconnect本身一直在升级，而当时它也没提供向后兼容。所以不想跟随他的版本一直不断升级。 至于是否能升级到5.0，要具体看他的源代码，看看加了什么内容。

近期会出一个不检测ankiconnect版本的更新。但要看有没有时间。

**Comment by FreeSlaver** [comment]
我看Anki Connect的整个都是Restful的接口，可以直接向本地发HTTP请求，在Chrome中不能这样做吗？

**Comment by pansila** [comment]
@songxin1990 就是用的restful，如果有兴趣可以自己改个提交上来，并不复杂。版本问题我提了个pull request，你可以试试看，注意词典数据data要自己导入，不然一直loading

**Comment by ninja33** [comment]
Fixed by PR #33 , will publish to web store recently.

**Comment by FreeSlaver** [comment]
@pansila  好的，我看看，怎么实现的。
