### ISSUE TITLE
浏览本地html文件时，底部的提示窗口不会自动调整

### ISSUE THREAD

**Issue by gsessylu** [ninja33/anki-dict-helper#34]
file:///*.html地址下，截图如下：
https://imgur.com/33rjJQU

**Comment by ninja33** [comment]
Thanks. It's been noted and reproduced. will fix it in next update.

**Comment by gsessylu** [comment]
Thanks for your work. And happy new year!

**Comment by gsessylu** [comment]
谢谢老黄^_^
