### ISSUE TITLE
Mac下面使用划词助手添加到anki的加号很久都不变绿

### ISSUE THREAD

**Issue by itgoyo** [ninja33/anki-dict-helper#36]
Mac下面使用划词助手添加到anki的加号很久都不变绿，但是在window下面基本都是按shift就和翻译一起出现的，请问这个是什么原因呢，ankiconnect文件也替换多了，chrome的anki也卸载重装过了，还是久久不能生成添加的按钮。
chrome 里面的选项，没有出现多选框，例如释义，发音这种，但是Windows系统下面是有的。
![](http://omvbl46i3.bkt.clouddn.com/42dd0e24da3aec4ef192fa1e4785e3ee.png)

**Comment by ninja33** [comment]
mac上要保持anki是激活状态，否则会不能制卡。详情可以看看插件作者的提示。
https://github.com/FooSoft/anki-connect#notes-for-mac-os-x-users

**Comment by itgoyo** [comment]
好的，谢谢在终端下面运行`defaults write net.ichi2.anki NSAppSleepDisabled -bool true`,已经可以添加了。
