### ISSUE TITLE
IndexedDB support

### ISSUE THREAD

**Issue by FooSoft** [ninja33/anki-dict-helper#4]
Just wanted to give you a heads up that I got IndexedDB up and running with Yomichan. It was quite a bit of work but it might be worth merging that functionality in, as it reduces memory usage significantly.

**Comment by ninja33** [comment]
wow! that's wonderful, thanks your info. 

Except reducing memory usage, don't know if it's possible to dynamically load local dictionary file in IndexedDB(file name & path can be defined in option page), I need double check the meaning of chrome permission "file://*/" in manifest.json.  Lots of  users in my English learning community want to choose English-Chinese dictionary freely by themselves(not pre-embedded in chrome extension) . Of course I can pre-complied different dictionaries in well-defined format, but it must be read by Chrome extension which seems not allowed by chrome security policy. emm, antoher solution is to put dictionaries on github and load it by XHR request. but if the file size is large, the first time loading will be quite time consume.

btw, I extended this addon connect ankiweb(use ankiweb id/password login in option page) to get deck & models/fields list, then users can one-click save card in ankiweb directly which I called this feature "cloud card maker", so users can make cards even without Anki PC client and ankiconnect installed. It will be very useful when users have no access to their primary PC, and it makes this extension has translation and card make all in one feature without any external dependencies

**Comment by FooSoft** [comment]
The ankiweb stuff you have going is looking pretty awesome. I will probably integrate that functionality into Yomichan. I agree that it would be ideal to be able to do all Anki-related features without requiring Anki to be running.

Regarding IndexedDB, I had two ideas for supporting user-provided dictionaries. We can provide a file upload form control, which would allow the user to upload the dictionary JSON data into the database. Another approach would be to allow the converter application to execute an HTTP server which would host the converted dictionaries. For Yomichan, I think I'm probably going to go with the second option since we are going to have to get the user to run the conversion software locally anyway, if we want to support proprietary/paid dictionaries.
