### ISSUE TITLE
一些国外网站的评论部分无法取词

### ISSUE THREAD

**Issue by wonderffee** [ninja33/anki-dict-helper#40]
正文取词正常，评论部分不能取词，比如这篇文章：https://appleinsider.com/articles/18/05/23/chinas-smartisan-says-apple-has-lost-its-soul-in-pitch-for-new-smartphone

**Comment by ninja33** [comment]
那个网站的评论部分是嵌在主网页的一个iframe。所以划词助手取不到iframe中的内容。暂时无法解决这个问题。

评论部分的网址在这里：https://forums.appleinsider.com/discussion/205616 在这个网页里，正文和评论都没有问题。
