### ISSUE TITLE
最近一次更新好像把词汇模板映射表里的信息清空了

### ISSUE THREAD

**Issue by wonderffee** [ninja33/anki-dict-helper#44]
不知道大家是不是都一样

**Comment by ninja33** [comment]
是的。为了和firefox统一代码，用storage.local 的接口代替了storage.sync
所以原来的配置信息要重新配置一边。

**Comment by wonderffee** [comment]
最好还是能平滑升级吧。还好我把原来的配置截图了，要不然重新配置一遍又得找字段。

**Comment by ninja33** [comment]
嗯，给你带来不便，表示歉意。

**Comment by wonderffee** [comment]
不用歉意，这么好的东东感谢还来不及，只是怕那些没保存配置的人有点蒙B，对于他们可能会麻烦一些
可以在readme里加上一个二维码方便打赏
