### ISSUE TITLE
能否选择关闭shift取词

### ISSUE THREAD

**Issue by sakuyamaij** [ninja33/anki-dict-helper#45]
先感谢大佬的插件。
平时自己英文写作比较多，需要用到Shift来大写首字母。
但是shift经常会触发插件的取词功能，使得英文输入的流畅度和效率大受影响。
请问能否选择关闭shift取词，或者提供一个自定义按键，将shift热键换成别的非常用按键。
谢谢。

**Comment by ninja33** [comment]
另一款名为在线词典助手的插件可以解决你的问题。该插件既可以更换划词热键，也会智能检测如果在输入区域，则不激活划词功能

**Comment by sakuyamaij** [comment]
谢谢解答。其实我是从那个换到这个来的...

**Comment by eMe-404** [comment]
我也遇到同样的问题，所以有解决方案吗，我想继续用anki单不想用shift来取词，能不能给个自定义按键，感谢
