### ISSUE TITLE
能否添加谷歌翻译(或其他翻译的api)，并且可以自定义源语言和目标语言？

### ISSUE THREAD

**Issue by Edenharder** [ninja33/anki-dict-helper#5]
如果能够有一个添加翻译api的选项会更好，划词显示翻译的时候只需要有单词以及api返回的翻译就行了。不知道我有没有表述清楚。如果能实现这一点的话，就可以用来学习其他语言或选择自己喜欢的翻译来源了。

谢谢您的贡献！

**Comment by ninja33** [comment]
谢谢你的建议。用在线翻译的内容用于制卡，这是个挺好的点子。不过这样就有外部依赖而且需要上网才能用。当然，这个可以在后台选项页面作为一个可选项，让用户选择是使用内置词典还是外置网络词典。

如果喜欢这个项目，也欢迎提交PR。

**Comment by Edenharder** [comment]
谢谢您的回复！作为可选项的确是个好的解决办法。

另外，建议项目主页面翻译成英文，中文的说明可以给个链接，然后放到到项目的wiki中。这么好的项目这样能吸引到更多的人吧。

**Comment by Edenharder** [comment]
请问您添加的在线翻译是用的有道的词典么？能否自定义呢？

**Comment by ninja33** [comment]
不可以自定义。翻译不是划词助手的重点，这类翻译插件市面上官方非官方的已经很多了。划词助手主要解决保存阅读现场（上下文例句，发音，网页网址）和配合Anki一键制卡。在Anki这个层面上，甚至有插件直接把词典的解释批量做成卡片。所以划词助手不准备在翻译内容上做过多的定制化和自定义。也就是满足一下阅读时不打断，让你看个大概意思就行了。

**Comment by Edenharder** [comment]
有一个疑问，划词助手所保存的例句并非网页中单词所在的句子，而是词典中的例句，是这样吧？

另外，[translate.js](https://github.com/Selection-Translator/translation.js)这个项目“收集多种翻译接口并用同一个 API 调用”。您其实不用自己去写调用有道翻译的代码，直接调用translate.js就好。划词助手定位于“划词助手主要解决保存阅读现场（上下文例句，发音，网页网址）和配合Anki一键制卡”，我的理解是划词助手是从单词到anki卡片的一个管道，管道的第一段是翻译(自带词典翻译和在线翻译)，之后是传送到anki。翻译这一段管道中的在线翻译这一部分其实可以用translate.js直接代替的，这样划词助手就不再是局限于英汉翻译了。希望您能考虑一下。

**Comment by ninja33** [comment]
1. 不是词典的例句，是网页中单词所在例句。不知道你有没有用过这个插件。

2. 另外，已经讲过了，翻译功能不是这个插件的重点，如果只是想制卡的话，甚至于可以完全不要翻译功能。有关翻译，不管用内置的，还是在线的翻译，一个是再造轮子，第二个总有人不满意的。Anki在词典查询方面，有很好的Anki插件 https://github.com/finalion/WordQuery  不管是有着丰富资源的mdx词典，还是有道，百度，vocabluary.com 都可以事后一键批量导入你喜欢的词典内的解释，而且原作者留了扩展接口，支持将来其他词典的扩展，词典这部分做在浏览器插件里太厚重了。而且在线查询有严重的时延和外部依赖，一旦不可用，非常影响阅读体验。

3. 有关英汉翻译的局限。翻译，不是简单拿个词头(headword)就可以去查词典的，因为单词的单复数，时态的原因，要先做去变形化(inflection)才能去词典查询，否则会大大影响词典的查询结果。对于其他语种，诸如德语，法语，西班牙语，俄语，词性变化差别很大。不了解该种语言的，简单拿个在线翻译的结果展示一下(目前大部分插件都是这种方式)，还不如不做。这部分要留给既懂该语言，又懂技术的人去进一步定制该语言的版本。

**Comment by Edenharder** [comment]
我的系统是Mac Os El captain 10.11.6，我对比了一下您介绍里的使用时的截图，发现我使用时单词所在行没有绿色加号。Firefox, Chrome都这样。
<img width="495" alt="screen shot 2017-01-16 at 8 38 34 am" src="https://cloud.githubusercontent.com/assets/6672134/21974502/8c56d9f8-dbc7-11e6-9ac8-bd8f6f2fad32.png">

**Comment by tooyond** [comment]
如果做成AwesomeTTS那样就完美了 ATTS是翻译语音 你可以翻译文字  有些内容不但是为了翻译 只是为了补充卡片内容 比如我现在的日语50音卡片 准备用罗马拼音加语音作为提示 记忆日文字形 因为前期录入时没添加这个字段 现在想补充上就很麻烦了 如果可以翻译成罗马拼音 那添加起来就轻松多了
